### ISSUE TITLE
Testing a Controller using Guardian.Phoenix.Controller

### ISSUE THREAD

**Issue by Dtatoo** [ueberauth/guardian#224]
I have controller logics using Guardian.Phoenix.Controller plug however when I am trying to test the controller it seems to be defaulting to Phoenix Controller.

When I included `use Guardian.Phoenix.Controller` on top of test file I am getting the following error. 
`** (CompileError) test/controllers/controller_test.exs:3: undefined function action_name/1`

Is there a way to configure test to use Guardian.Phoenix.Controller?

**Comment by doomspork** [comment]
Hi @Dtatoo, do you have a project on GitHub I could look at?

**Comment by Dtatoo** [comment]
The project is still under active development and marked as private. However I did create a copy and pasted version of controller and test I am using uploaded to Gist.
https://gist.github.com/Dtatoo/6d58933681a790bad43d5adbe8c76309

Let me know for whatever reason you would like to view the whole project. I am using basic Phoenix stack setup.

**Comment by scrogson** [comment]
@Dtatoo this error is due to including `use Guardian.Phoenix.Controller` in your test file. This module is only intended to be included in your controller module as it simply overrides the default `action/2` function which is injected by Phoenix.

Removing [this line](https://gist.github.com/Dtatoo/6d58933681a790bad43d5adbe8c76309#file-clinic_controller_test-exs-L3) should get you passed the error.

You will also need to add the additional `user` and `claims` arguments to the remaining controller actions in your controller as well.
