### ISSUE TITLE
Can't set custom serializer when generating token

### ISSUE THREAD

**Issue by koriroys** [ueberauth/guardian#245]
I noticed that you can override the default serializer when you call `Guardian.Plug.LoadResource`, but you can't override it when you create the original token (`Guardian.Plug.api_sign_in`, `Guardian.Plug.sign_in`, `Guardian.encode_and_sign`). I can see having two or more different resources to load in a single app. In that case, would you want separate serializers for each resource? Would this be a feature worth providing, or is the serializer option for `LoadResource` only intended for testing? (seems to be the original intent based on history)

**Comment by doomspork** [comment]
Howdy @koriroys, the `:serializer` was introduced in an earlier PR for the purpose of making testing easier: https://github.com/ueberauth/guardian/pull/188#issue-172057601

In my applications I rely on a single serializer for all of my resources because it keeps things in one place and there's rarely much logic to them.
