### ISSUE TITLE
Authenticating socket with cookie

### ISSUE THREAD

**Issue by madshargreave** [ueberauth/guardian#246]
Hi

I am currently using the authentication scheme for HTTP requests and websocket communication.

I am storing a cookie in the browser using Guardian which works fine. 

When it comes to sockets, I see that I must pass in the JWT explicitly, which is a problem due to the cookie being HTTP only.

How do I get around this?

**Comment by scrogson** [comment]
@madshargreave is this question directed at Phoenix Channel socket authentication?

If so, there are a couple of options for this:

* Create a normal HTTP API endpoint on the server that a client can use to fetch a token based on the value in the cookie.
* Render a token into the DOM and query it with JS.

Because Phoenix Channels were designed to not be coupled to browsers, cookie-based authentication is not supported.
