### ISSUE TITLE
Guardian.Plug.sign_in silent failure and possible information disclosure

### ISSUE THREAD

**Issue by lukaszsamson** [ueberauth/guardian#374]
Guardian version: 0.14.5
Current behavior:
When `Guardian.Plug.sign_in` is not able to succeed (e.g. when `Guardian.Serializer` returns `{:error, reason}`) the function returns successfully and puts potentially confidential error details in session which is then sent to the client.
Expected behavior:
Error risen when sign in does not succeed
Error details not leaked

**Comment by hassox** [comment]
hey @lukaszsamson 

What you describe is the behaviour in the new 1.0 branch. There's a couple of options for us on the 0.14.x branch.

1. Add a function that wraps and raises
2. We add it to Guardian 0.14.x

I'm partial to option 1 at the moment since I believe that v1 is strictly better than 0.14.x and would like to focus our energies there. Having said that if you wanted to add a function that is a raise version I wouldn't be against adding it to the 0.14.x branch.

**Comment by scrogson** [comment]
This bug has been addressed in `v1.0.0`. We will be releasing `v1.0.0-beta.0` to hex very soon. Please follow the upgrade guide and please be sure to let us know if you have any trouble.

Thank you!
