### ISSUE TITLE
Programmatically invalidate all existing tokens?

### ISSUE THREAD

**Issue by johnnyji** [ueberauth/guardian#438]
Hi there!

I was wondering if there was a way to invalidate all existing tokens? The example use case would be deploying some new code to production that would require all users to log out?

Please let me know if this is currently possible with Guardian. I didn't seem to see it anywhere in the documentation.

Thanks for the amazing library 👍

**Comment by yordis** [comment]
Guardian do not show any example right now because how you do it is really up to your needs and your application. Specially that Guardian allow you to create your own tokens and stuff like that so I will explain a little bit about JWT tokens (if you change your token then your strategy will change wit it)

For invalidate JWT tokens you will need to change your encryption keys or wait until the expiration time of the JWT makes the token invalid or you could use `Guardian.DB` which pretty much do some database look up for your token.

If you are not familiar with JWT details I would suggest you to add `Guardian.DB` until it becomes a problem (probably you will have enough money for do the changes to be honest 😄 ) but this will defeat the reason why you use JWT (statelessness tokens).

JWT security model is based on encryption mechanism where you trust that there is no way for somebody to know how to properly encrypt the token without using your application (it is the one that knows about it). The encryption uses your private `secret_key` for be able to encode and decode the token.

## Actual answer

- Change your `secret_key` 🔴 🔴 🔴 This will `invalidate all the tokens` in your application because the decoding will fail (the secret key used for the encoding is not longer the same). So restart the server with new keys or whatever mechanism you used for the secret key.
- Use `Guardian.DB`, pretty much it does a database look up for make sure that your token is there, so you will need to clean your database table information for invalidate the tokens.

Let me know if you need any help, from your example, just change the `secret key` it will make all the tokens invalid.

**Comment by johnnyji** [comment]
@yordis Thank you for the amazingly detailed explanation! I can't believe I didn't think of just resetting the secret key haha
