### ISSUE TITLE
RS256

### ISSUE THREAD

**Issue by MeterSoft** [ueberauth/guardian#485]
I tried to decode RS256 access code but it returns error
Olist.Guardian.decode_and_verify(token)
{:error, :invalid_token}
```elixir
# config

config :olist, Olist.Guardian,
   issuer: "olist",
   secret_key: "3UpoE1SvErp2GKrS7fj+uWUWI05EoF0w/0YcE7cVDKjakTr7nKqxWRt61GkJsCZr",
   verify_module: Guardian.JWT,
   allowed_algos: ["RS256"]


defmodule Olist.Guardian do
  use Guardian, otp_app: :olist
end
```

**Comment by pauldoerwald** [comment]
I just realized something: RS256 uses public keys, which explains why the secret key I have doesn't work... I need to use my Auth0 public key... I think. Maybe HS256/HS512 is the right approach...

**Comment by pauldoerwald** [comment]
As always happens, as soon as I start asking for help, I figure it out.

The problem above was how I was specifying the secret_key. It should be something more like:

config :clockk, Clockk.Guardian,
      allowed_algos: ["HS512"],
      issuer: "clockk.auth0.com",
      secret_key: fn ->
        "-----BEGIN CERTIFICATE-----
    certificate goes here. Ordinarily you would keep this in a file which you would load, but I'm putting it inline for simplicity.
    -----END CERTIFICATE-----
    "
        |> Kernel.||("")
        |> String.replace("\\n", "\n")
        |> JOSE.JWT.from_pem
      end

With this `secret_key`, things start to work. However, because of the argument in https://github.com/ueberauth/guardian/issues/152 which points out that RSA keys are VERY slow and thus inappropriate for Bearer authorization, I'm switching to HS256 which works much more like what @MeterSoft above did.

**Comment by yordis** [comment]
@pauldoerwald thanks a lot for the research, I am happy that you figured it out.

@MeterSoft feel free to reopen it if you think this still an issue for you but please follow @pauldoerwald instructions first.

**Comment by jaybe78** [comment]
@yordis  Spent the whole day on this  and I was able to make it work for HS256 but as for me whatever I do RS256 algo never works !

I've verified EVERYTHING!!
If my implementation was incorrect, I guess I would not even be able to make it work for HS256 either, so I guess something must be wrong
