### ISSUE TITLE
can not install on Phoenix 1.4.0-rc

### ISSUE THREAD

**Issue by lmcardle** [ueberauth/guardian#529]
I am unable to install this on a new project I am using Phoenix 1.4.0-rc. I get the error: 
```
Failed to use "phoenix" (version 1.4.0-rc.1) because
  guardian (versions 1.1.0 and 1.1.1) requires ~> 1.0 or ~> 1.2 or ~> 1.3 *
```

**Comment by yordis** [comment]
I believe that until `1.4` is released we can't take ownership of the issues that could potentially happen.

The reason, as a release candidate, things could change and break over and over so it is better to wait until the finale release of it, unless @ueberauth/core think otherwise.

In the mid-time, you could add fork the repo and change this deps to include `1.4` https://github.com/ueberauth/guardian/blob/b19f2c96824279e231f7da82471245a090b524d1/mix.exs#L162 and use your fork as the dependency of guardian.

After `1.4` is release, please open a PR updating the configuration if you dont mind.

**Comment by cultofmetatron** [comment]
Just made a fork with the versions bumped [https://github.com/cultofmetatron/guardian](https://github.com/cultofmetatron/guardian).

I plan to full ham with this on a 1.4 app and fix issues as I run into them. Feel free to submit PRs.

**Comment by johannestroeger** [comment]
isn't this a good opportunity to replace `Poison` with `Jason`? or make it at least configurable like [ecto](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#json-handling) does it?

**Comment by yordis** [comment]
@johannestroeger open a new issue with your suggestion so I can circle back to this.

When we use `Poison` or `Jason` shouldn't matter and it shouldn't break anything

**Comment by garretttaco** [comment]
I was able to install this on a Phoenix 1.4 project, should we close this out?
