### ISSUE TITLE
Any telemetry?

### ISSUE THREAD

**Issue by delitescere** [ueberauth/guardian#673]
Is there a mechanism to incorporate telemetry into guardian so metrics are captured?

**Comment by Hanspagh** [comment]
We don't have this as of now, feel free to suggest some events that you would find relevant.

**Comment by yordis** [comment]
@delitescere feel free to open the issue and suggest some telemetries, in the best we wouldn't need to add such thing to Guardian, related to: https://dev.to/savonarola/why-solid-may-be-useful-for-you-in-elixir-58me

So I am curious to see exactly what needs to be extended in order to achieve your decided telemetry
